version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: seifjackson-site:latest
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production


